import {config} from './config.js';
import {run} from './process.js';
const base=()=>{const a=[];if(config.ytDlpScript)a.push(config.ytDlpScript);a.push('--no-playlist','--no-warnings','--ignore-config','--socket-timeout','30');if(config.cookiesFile)a.push('--cookies',config.cookiesFile);return a};
export function normalizeInfo(x){return{id:x.id??null,title:x.title??null,uploader:x.uploader??x.channel??null,channel:x.channel??null,duration:x.duration==null?null:Number(x.duration),thumbnail:x.thumbnail??null,webpage_url:x.webpage_url??null,extractor:x.extractor??null,live:Boolean(x.is_live),upload_date:x.upload_date??null,view_count:x.view_count??null,like_count:x.like_count??null,description:x.description??null,width:x.width??null,height:x.height??null,fps:x.fps??null,ext:x.ext??null,formats:Array.isArray(x.formats)?x.formats.map(f=>({id:f.format_id??null,ext:f.ext??null,resolution:f.resolution??null,width:f.width??null,height:f.height??null,fps:f.fps??null,filesize:f.filesize??f.filesize_approx??null,vcodec:f.vcodec??null,acodec:f.acodec??null,quality:f.quality??null,format_note:f.format_note??null})):[]}};
export async function inspect(url){const r=await run(config.ytDlp,[...base(),'--dump-single-json',url],{timeout:Math.min(config.processTimeout,120000)}).promise;try{return normalizeInfo(JSON.parse(r.stdout))}catch{throw new Error('yt-dlp returned invalid metadata')}}
export function videoSelector(q){if(q==='best')return'bv*+ba/b';const n=Number(q);if(![144,240,360,480,720,1080,1440,2160].includes(n))throw new Error('Unsupported video quality');return`bv*[height<=${n}]+ba/b[height<=${n}]`}
export function audioSelector(q){if(q==='best')return'bestaudio/best';const n=Number(q);if(![64,96,128,160,192,256,320].includes(n))throw new Error('Unsupported audio bitrate');return'bestaudio/best'}
export function audioQuality(q){if(q==='best')return'0';const n=Number(q);if(![64,96,128,160,192,256,320].includes(n))throw new Error('Unsupported audio bitrate');return`${n}K`}
export async function assertDuration(url){const info=await inspect(url);if(info.duration!=null&&info.duration>config.maxDuration)throw new Error(`Media exceeds MAX_DURATION_SECONDS (${config.maxDuration})`);return info}
